/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package docklandsbikemanager;

/**
 *
 * @author ryanl
 */
public class MainGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainGUI.class.getName());
    private BikeSystemManager manager = new BikeSystemManager();
    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        TBStationM = new javax.swing.JPanel();
        stationIdLBL = new javax.swing.JLabel();
        stationNameLBL = new javax.swing.JLabel();
        locationLBL = new javax.swing.JLabel();
        capacityLBL = new javax.swing.JLabel();
        stationIdTF = new javax.swing.JTextField();
        stationNameTF = new javax.swing.JTextField();
        locationTF = new javax.swing.JTextField();
        capacityTF = new javax.swing.JTextField();
        addBTN = new javax.swing.JButton();
        viewBTN = new javax.swing.JButton();
        removeBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        stationTA = new javax.swing.JTextArea();
        stationInfoLBL = new javax.swing.JLabel();
        BikeManagmentTAB = new javax.swing.JPanel();
        bikeIdLBL = new javax.swing.JLabel();
        mTypeLBL = new javax.swing.JLabel();
        bLevelLBL = new javax.swing.JLabel();
        BikeTypeLBL = new javax.swing.JLabel();
        bikeIdTF = new javax.swing.JTextField();
        modelTypeTF = new javax.swing.JTextField();
        batteryLevelTF = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        bikeTA = new javax.swing.JTextArea();
        removeBikeBTN = new javax.swing.JButton();
        addBikeBTN = new javax.swing.JButton();
        viewBikesBTN = new javax.swing.JButton();
        statusLBL = new javax.swing.JLabel();
        statusTF = new javax.swing.JTextField();
        bikeTypeCB = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        MQueueTAB = new javax.swing.JPanel();
        bikeLBL = new javax.swing.JLabel();
        maintenanceBikeTF = new javax.swing.JTextField();
        sendMaintenanceBTN = new javax.swing.JButton();
        processMaintenanceBTN = new javax.swing.JButton();
        viewQueueBTN = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        queueTA = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        stationIdLBL.setText("Station ID :");

        stationNameLBL.setText("Station Name :");

        locationLBL.setText("Location :");

        capacityLBL.setText("Capacity :");

        addBTN.setText("Add Station");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        viewBTN.setText("View Stations");
        viewBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBTNActionPerformed(evt);
            }
        });

        removeBTN.setText("Remove Station");
        removeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBTNActionPerformed(evt);
            }
        });

        stationTA.setColumns(20);
        stationTA.setRows(5);
        jScrollPane1.setViewportView(stationTA);

        stationInfoLBL.setText("Station Information :");

        javax.swing.GroupLayout TBStationMLayout = new javax.swing.GroupLayout(TBStationM);
        TBStationM.setLayout(TBStationMLayout);
        TBStationMLayout.setHorizontalGroup(
            TBStationMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TBStationMLayout.createSequentialGroup()
                .addGroup(TBStationMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TBStationMLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(TBStationMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(capacityLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(locationLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stationNameLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stationIdLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TBStationMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TBStationMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(stationIdTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                .addComponent(stationNameTF))
                            .addComponent(locationTF, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(capacityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(TBStationMLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(TBStationMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(TBStationMLayout.createSequentialGroup()
                                .addComponent(addBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(removeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                .addGroup(TBStationMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stationInfoLBL))
                .addGap(29, 29, 29))
        );
        TBStationMLayout.setVerticalGroup(
            TBStationMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TBStationMLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(stationInfoLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TBStationMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TBStationMLayout.createSequentialGroup()
                        .addGroup(TBStationMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stationIdLBL)
                            .addComponent(stationIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(TBStationMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stationNameLBL)
                            .addComponent(stationNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(TBStationMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(locationLBL)
                            .addComponent(locationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(TBStationMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(capacityLBL)
                            .addComponent(capacityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(TBStationMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBTN)
                            .addComponent(removeBTN))
                        .addGap(18, 18, 18)
                        .addComponent(viewBTN))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Station Management", TBStationM);

        bikeIdLBL.setText("Bike ID :");

        mTypeLBL.setText("Model Type :");

        bLevelLBL.setText("Battery Level :");

        BikeTypeLBL.setText("Bike Type:");

        bikeTA.setColumns(20);
        bikeTA.setRows(5);
        jScrollPane2.setViewportView(bikeTA);

        removeBikeBTN.setText("Remove Bike");
        removeBikeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBikeBTNActionPerformed(evt);
            }
        });

        addBikeBTN.setText("Add Bike");
        addBikeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBikeBTNActionPerformed(evt);
            }
        });

        viewBikesBTN.setText("View Bikes");
        viewBikesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBikesBTNActionPerformed(evt);
            }
        });

        statusLBL.setText("Status :");

        bikeTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "StandardBike", "ElectricBike" }));

        jLabel1.setText("Bike Information: ");

        javax.swing.GroupLayout BikeManagmentTABLayout = new javax.swing.GroupLayout(BikeManagmentTAB);
        BikeManagmentTAB.setLayout(BikeManagmentTABLayout);
        BikeManagmentTABLayout.setHorizontalGroup(
            BikeManagmentTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BikeManagmentTABLayout.createSequentialGroup()
                .addGroup(BikeManagmentTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BikeManagmentTABLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(BikeManagmentTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BikeManagmentTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BikeManagmentTABLayout.createSequentialGroup()
                                    .addComponent(bikeIdLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(54, 54, 54))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BikeManagmentTABLayout.createSequentialGroup()
                                    .addComponent(mTypeLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(25, 25, 25))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BikeManagmentTABLayout.createSequentialGroup()
                                    .addComponent(statusLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(50, 50, 50))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BikeManagmentTABLayout.createSequentialGroup()
                                    .addComponent(bLevelLBL)
                                    .addGap(28, 28, 28)))
                            .addGroup(BikeManagmentTABLayout.createSequentialGroup()
                                .addComponent(BikeTypeLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(BikeManagmentTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(batteryLevelTF)
                            .addComponent(modelTypeTF)
                            .addComponent(bikeIdTF)
                            .addComponent(statusTF)
                            .addComponent(bikeTypeCB, 0, 184, Short.MAX_VALUE)))
                    .addGroup(BikeManagmentTABLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(BikeManagmentTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewBikesBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(BikeManagmentTABLayout.createSequentialGroup()
                                .addComponent(addBikeBTN)
                                .addGap(45, 45, 45)
                                .addComponent(removeBikeBTN)))))
                .addGap(89, 89, 89)
                .addGroup(BikeManagmentTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(0, 178, Short.MAX_VALUE))
        );
        BikeManagmentTABLayout.setVerticalGroup(
            BikeManagmentTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BikeManagmentTABLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(BikeManagmentTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bikeIdLBL)
                    .addComponent(bikeIdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BikeManagmentTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mTypeLBL)
                    .addComponent(modelTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BikeManagmentTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLBL)
                    .addComponent(statusTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BikeManagmentTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(batteryLevelTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLevelLBL))
                .addGap(24, 24, 24)
                .addGroup(BikeManagmentTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BikeTypeLBL)
                    .addComponent(bikeTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(BikeManagmentTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeBikeBTN)
                    .addComponent(addBikeBTN))
                .addGap(18, 18, 18)
                .addComponent(viewBikesBTN)
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BikeManagmentTABLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        bikeTypeCB.getAccessibleContext().setAccessibleParent(BikeTypeLBL);

        jTabbedPane1.addTab("Bike Managment", BikeManagmentTAB);

        bikeLBL.setText("Bike Index");

        sendMaintenanceBTN.setText("Send To Maintenance");
        sendMaintenanceBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMaintenanceBTNActionPerformed(evt);
            }
        });

        processMaintenanceBTN.setText("Process Next Bike");
        processMaintenanceBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processMaintenanceBTNActionPerformed(evt);
            }
        });

        viewQueueBTN.setText("View Queue");
        viewQueueBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewQueueBTNActionPerformed(evt);
            }
        });

        queueTA.setColumns(20);
        queueTA.setRows(5);
        jScrollPane3.setViewportView(queueTA);

        javax.swing.GroupLayout MQueueTABLayout = new javax.swing.GroupLayout(MQueueTAB);
        MQueueTAB.setLayout(MQueueTABLayout);
        MQueueTABLayout.setHorizontalGroup(
            MQueueTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MQueueTABLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(MQueueTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewQueueBTN)
                    .addComponent(processMaintenanceBTN)
                    .addComponent(sendMaintenanceBTN)
                    .addGroup(MQueueTABLayout.createSequentialGroup()
                        .addComponent(bikeLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maintenanceBikeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
        );
        MQueueTABLayout.setVerticalGroup(
            MQueueTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MQueueTABLayout.createSequentialGroup()
                .addGroup(MQueueTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MQueueTABLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(MQueueTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bikeLBL)
                            .addComponent(maintenanceBikeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(sendMaintenanceBTN)
                        .addGap(38, 38, 38)
                        .addComponent(processMaintenanceBTN)
                        .addGap(38, 38, 38)
                        .addComponent(viewQueueBTN))
                    .addGroup(MQueueTABLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Maintenance Queue", MQueueTAB);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1076, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        String stationId = stationIdTF.getText();
        String stationName = stationNameTF.getText();
        String location = locationTF.getText();
        int capacity = Integer.parseInt(capacityTF.getText());
        
        BikeStation station = new BikeStation(stationId,stationName, location, capacity);
        manager.addStation(station);
        
        stationTA.setText(manager.viewStations());
        
        stationIdTF.setText("");
        stationNameTF.setText("");
        locationTF.setText("");
        capacityTF.setText("");
        
        
    }//GEN-LAST:event_addBTNActionPerformed

    private void viewBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBTNActionPerformed
        // TODO add your handling code here:
        stationTA.setText(manager.viewStations());
    }//GEN-LAST:event_viewBTNActionPerformed

    private void removeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBTNActionPerformed
        // TODO add your handling code here:
        int index = Integer.parseInt(stationIdTF.getText());
        manager.removeStation(index);
        stationTA.setText(manager.viewStations());
        stationIdTF.setText("");
    }//GEN-LAST:event_removeBTNActionPerformed

    private void addBikeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBikeBTNActionPerformed
        // TODO add your handling code here:
        
        String bikeId = bikeIdTF.getText();
        String modelType = modelTypeTF.getText();
        String status = statusTF.getText();
        String bikeType = bikeTypeCB.getSelectedItem().toString();

        Bike bike;

        if (bikeType.equals("ElectricBike")) {
            int batteryLevel = Integer.parseInt(batteryLevelTF.getText());
            bike = new ElectricBike(bikeId, modelType, status, batteryLevel);
        } else {
            bike = new StandardBike(bikeId, modelType, status);
        }

        manager.addBike(bike);
        bikeTA.setText(manager.viewBikes());

        bikeIdTF.setText("");
        modelTypeTF.setText("");
        statusTF.setText("");
        batteryLevelTF.setText("");
        
    }//GEN-LAST:event_addBikeBTNActionPerformed

    private void viewBikesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBikesBTNActionPerformed
        // TODO add your handling code here:
        bikeTA.setText(manager.viewBikes());
        
    }//GEN-LAST:event_viewBikesBTNActionPerformed

    private void removeBikeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBikeBTNActionPerformed
        // TODO add your handling code here:
        int index = Integer.parseInt(bikeIdTF.getText());
        manager.removeBike(index);
        bikeTA.setText(manager.viewBikes());
        
        bikeIdTF.setText("");
    }//GEN-LAST:event_removeBikeBTNActionPerformed

    private void viewQueueBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewQueueBTNActionPerformed
        // TODO add your handling code here:
        queueTA.setText(manager.viewQueue());
    }//GEN-LAST:event_viewQueueBTNActionPerformed

    private void sendMaintenanceBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMaintenanceBTNActionPerformed
        // TODO add your handling code here:
        int index = Integer.parseInt(maintenanceBikeTF.getText());
        Bike bike = (Bike) manager.getBikesList().get(index);
        
        manager.sendToMaintenance(bike);
        queueTA.setText(manager.viewQueue());
        
        maintenanceBikeTF.setText("");
    }//GEN-LAST:event_sendMaintenanceBTNActionPerformed

    private void processMaintenanceBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processMaintenanceBTNActionPerformed
        // TODO add your handling code here:
        Object processedBike = manager.processMaintenance();
        queueTA.setText("Processed: " + processedBike + "\n" + manager.viewQueue());
    }//GEN-LAST:event_processMaintenanceBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BikeManagmentTAB;
    private javax.swing.JLabel BikeTypeLBL;
    private javax.swing.JPanel MQueueTAB;
    private javax.swing.JPanel TBStationM;
    private javax.swing.JButton addBTN;
    private javax.swing.JButton addBikeBTN;
    private javax.swing.JLabel bLevelLBL;
    private javax.swing.JTextField batteryLevelTF;
    private javax.swing.JLabel bikeIdLBL;
    private javax.swing.JTextField bikeIdTF;
    private javax.swing.JLabel bikeLBL;
    private javax.swing.JTextArea bikeTA;
    private javax.swing.JComboBox<String> bikeTypeCB;
    private javax.swing.JLabel capacityLBL;
    private javax.swing.JTextField capacityTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel locationLBL;
    private javax.swing.JTextField locationTF;
    private javax.swing.JLabel mTypeLBL;
    private javax.swing.JTextField maintenanceBikeTF;
    private javax.swing.JTextField modelTypeTF;
    private javax.swing.JButton processMaintenanceBTN;
    private javax.swing.JTextArea queueTA;
    private javax.swing.JButton removeBTN;
    private javax.swing.JButton removeBikeBTN;
    private javax.swing.JButton sendMaintenanceBTN;
    private javax.swing.JLabel stationIdLBL;
    private javax.swing.JTextField stationIdTF;
    private javax.swing.JLabel stationInfoLBL;
    private javax.swing.JLabel stationNameLBL;
    private javax.swing.JTextField stationNameTF;
    private javax.swing.JTextArea stationTA;
    private javax.swing.JLabel statusLBL;
    private javax.swing.JTextField statusTF;
    private javax.swing.JButton viewBTN;
    private javax.swing.JButton viewBikesBTN;
    private javax.swing.JButton viewQueueBTN;
    // End of variables declaration//GEN-END:variables
}
